#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl11, sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port8,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           clawMotor,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*----------------------------------------------------------------------------------------------------*\
|*                                   			  - Verkefni 4 -              		                      	  *|
|*                                    ROBOTC on VEX 2.0 CORTEX                                        *|
|* In this program the robot will start when the lights turn on and it will use the sensor that it has*|
|*      													to drive without hitting anything   															  *|
|       																																															*|
\*----------------------------------------------------------------------------------------------------*/


const float WHEELBASE = 3.33;




void TurnRight (int deg)
{
	while (abs(SensorValue[rightEncoder]) < deg * WHEELBASE)
	{
		if(vexRT[Btn7D] == 1)//if button 7 D is pressed the motor stops
		{
			motor(rightMotor) = 0;
			motor(leftMotor) = 0;
		}
		else
			{
			motor[leftMotor] = -127;
			motor[rightMotor] = 127;
			}
	}
}

void TurnLeft (int deg)
{
	while (abs(SensorValue[leftEncoder]) < deg * WHEELBASE)
	{
		if(vexRT[Btn7D] == 1)//if button 7 D is pressed the motor stops
		{
			motor(rightMotor) = 0;
			motor(leftMotor) = 0;
		}
		else
		{
			motor[leftMotor] = 127;
			motor[rightMotor] = -127;
		}
	}
}

void drive(){
	while(1 == 1)		// Creates an infinite loop, since "true" always evaluates to true
		{
				// Turn slightly right
				motor[rightMotor] = 60;
				motor[leftMotor]  = 80;
		}
}

void ResetEncoder()
{
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;


}
//when button 7d is pressed stops all tasks
task Stop()
{
	while (vexRT[Btn7D] == 0)
	{

	}
	StopAllTasks();
}

task main()
{
	 StartTask(Stop);
	 while(SensorValue(lightSensor) < 300) // While the ambient lightSensor reads a value less than 300
		{

			for(int i = 1; i < 1000; i++)
			{
				while(SensorValue(sonarSensor) > 50  || SensorValue(sonarSensor) == -1)//the robot will drive when the sonar cant sense a object within 30 cm
				{
					motor[rightMotor] = 60;		    // Right Motor is run at power level 60
					motor[leftMotor]  = 80;
				}

				if(SensorValue(sonarSensor) = 50  || SensorValue(sonarSensor) == -1)//if robot gets 30 cm close to an object the robot will turn
				{
					ResetEncoder();
					TurnLeft(90);

				}

		 }
	 }

	while(SensorValue(lightSensor) > 300) // While the ambient lightSensor reads a value less than 300
	{

	}
}
