#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  	This program makes the robot go 0.5m forward then 0.5m backwards and the 1.0m forward and 1.0m	*|
|*		backwards until you reach 2.5m																																	*|
|*                                                   																									*|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Power levels that can be assigned to a motor port range from -127 (full reverse) to         *|
|*        127 (full forward).                                                                         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
\*-----------------------------------------------------------------------------------------------4246-*/
const int FULL_POWER = 127;
const int BASE_TIME = 1000;
bool b_f = true;

void drive(int drivetime, bool b_f){
	int dir = (b_f)? (1):(-1);
	motor[rightMotor] = FULL_POWER*dir;
	motor[leftMotor]  = FULL_POWER*dir;
	wait1Msec(drivetime);

}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(1000);
	for(int i=1;i<6;i++){
	drive(BASE_TIME*i,true);
	drive(BASE_TIME*i,false);
	}
}
//++++++++++++++++
